# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: JJK.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'JJK.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tJJK.proto\x12\nOcto.Proto\"\xb8\x02\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\x0b\n\x03\x63rc\x18\x05 \x01(\r\x12\x0b\n\x03md5\x18\x06 \x01(\t\x12\x10\n\x08priority\x18\x07 \x01(\x05\x12\r\n\x05tagid\x18\x08 \x03(\x05\x12\x13\n\x0b\x64\x65pendencie\x18\t \x03(\x05\x12\x12\n\nobjectName\x18\n \x01(\t\x12\x12\n\ngeneration\x18\x0b \x01(\x04\x12\x17\n\x0fuploadVersionId\x18\x0c \x01(\x05\x12%\n\x05state\x18\r \x01(\x0e\x32\x16.Octo.Proto.Data.State\">\n\x05State\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06LATEST\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\"\x93\x01\n\x08\x44\x61tabase\x12\x10\n\x08revision\x18\x01 \x01(\x05\x12)\n\x0f\x61ssetBundleList\x18\x02 \x03(\x0b\x32\x10.Octo.Proto.Data\x12\x0f\n\x07tagname\x18\x03 \x03(\t\x12&\n\x0cresourceList\x18\x04 \x03(\x0b\x32\x10.Octo.Proto.Data\x12\x11\n\turlFormat\x18\x05 \x01(\t\"h\n\x03Url\x12\x10\n\x08revision\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12$\n\x05state\x18\x03 \x01(\x0e\x32\x15.Octo.Proto.Url.State\"\x1c\n\x05State\x12\n\n\x06LATEST\x10\x01\x12\x07\n\x03OLD\x10\x02\"\'\n\x07UrlList\x12\x1c\n\x03url\x18\x01 \x03(\x0b\x32\x0f.Octo.Proto.Url')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JJK_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=26
  _globals['_DATA']._serialized_end=338
  _globals['_DATA_STATE']._serialized_start=276
  _globals['_DATA_STATE']._serialized_end=338
  _globals['_DATABASE']._serialized_start=341
  _globals['_DATABASE']._serialized_end=488
  _globals['_URL']._serialized_start=490
  _globals['_URL']._serialized_end=594
  _globals['_URL_STATE']._serialized_start=566
  _globals['_URL_STATE']._serialized_end=594
  _globals['_URLLIST']._serialized_start=596
  _globals['_URLLIST']._serialized_end=635
# @@protoc_insertion_point(module_scope)
